@WebAPI_HostAddress = https://localhost:7107

GET {{WebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebAPI_HostAddress}}/api/refuel
Content-Type: application/json

{
  //Refuel
}

###
